name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["master"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.3
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          user: rudisimo
          template: classic
          base: header, activity, community, repositories, metadata
          config_animated: yes
          config_timezone: America/New_York
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_lines: yes
